import React, { ReactNode } from 'react';
import Head from 'next/head';
import NavBar from './NavBar';
import HeaderHero from './HeaderHero';

type Props = {
  children?: ReactNode;
  title?: string;
};

const Layout = ({ children, title = 'Blbý otázky' }: Props) => (
    <div className="bg-gray-100 min-h-screen">
        <div className="container mx-auto">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>{children}</main>
            <footer className="mt-4">
            {/* Footer content goes here */}
            </footer>
        </div>
    </div>
);

export default Layout;
