# Generated by Django 4.2 on 2023-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_stupidquestionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="stupidquestionitem",
            name="score",
            field=models.SmallIntegerField(default=0),
        ),
    ]
